/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeaknessesRouteImport } from './routes/weaknesses'
import { Route as TypeChartRouteImport } from './routes/type-chart'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as GameGenerationRouteImport } from './routes/game.$generation'
import { Route as BackendProxySplatRouteImport } from './routes/backend-proxy/$'
import { Route as ApiPokemonPoolsRouteImport } from './routes/api.pokemon-pools'
import { Route as ApiPokemonCaptureGuideRouteImport } from './routes/api.pokemon-capture-guide'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsAdminRouteImport } from './routes/_authenticated/settings.admin'

const WeaknessesRoute = WeaknessesRouteImport.update({
  id: '/weaknesses',
  path: '/weaknesses',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeChartRoute = TypeChartRouteImport.update({
  id: '/type-chart',
  path: '/type-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGenerationRoute = GameGenerationRouteImport.update({
  id: '/game/$generation',
  path: '/game/$generation',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendProxySplatRoute = BackendProxySplatRouteImport.update({
  id: '/backend-proxy/$',
  path: '/backend-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPokemonPoolsRoute = ApiPokemonPoolsRouteImport.update({
  id: '/api/pokemon-pools',
  path: '/api/pokemon-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPokemonCaptureGuideRoute = ApiPokemonCaptureGuideRouteImport.update({
  id: '/api/pokemon-capture-guide',
  path: '/api/pokemon-capture-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAdminRoute =
  AuthenticatedSettingsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/type-chart': typeof TypeChartRoute
  '/weaknesses': typeof WeaknessesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/teams': typeof AuthenticatedTeamsRoute
  '/api/pokemon-capture-guide': typeof ApiPokemonCaptureGuideRoute
  '/api/pokemon-pools': typeof ApiPokemonPoolsRoute
  '/backend-proxy/$': typeof BackendProxySplatRoute
  '/game/$generation': typeof GameGenerationRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$username': typeof UUsernameRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/type-chart': typeof TypeChartRoute
  '/weaknesses': typeof WeaknessesRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/api/pokemon-capture-guide': typeof ApiPokemonCaptureGuideRoute
  '/api/pokemon-pools': typeof ApiPokemonPoolsRoute
  '/backend-proxy/$': typeof BackendProxySplatRoute
  '/game/$generation': typeof GameGenerationRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$username': typeof UUsernameRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/type-chart': typeof TypeChartRoute
  '/weaknesses': typeof WeaknessesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/api/pokemon-capture-guide': typeof ApiPokemonCaptureGuideRoute
  '/api/pokemon-pools': typeof ApiPokemonPoolsRoute
  '/backend-proxy/$': typeof BackendProxySplatRoute
  '/game/$generation': typeof GameGenerationRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/play'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/type-chart'
    | '/weaknesses'
    | '/settings'
    | '/teams'
    | '/api/pokemon-capture-guide'
    | '/api/pokemon-pools'
    | '/backend-proxy/$'
    | '/game/$generation'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/u/$username'
    | '/settings/admin'
    | '/settings/profile'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/play'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/type-chart'
    | '/weaknesses'
    | '/teams'
    | '/api/pokemon-capture-guide'
    | '/api/pokemon-pools'
    | '/backend-proxy/$'
    | '/game/$generation'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/u/$username'
    | '/settings/admin'
    | '/settings/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/play'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/type-chart'
    | '/weaknesses'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/api/pokemon-capture-guide'
    | '/api/pokemon-pools'
    | '/backend-proxy/$'
    | '/game/$generation'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/u/$username'
    | '/_authenticated/settings/admin'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TypeChartRoute: typeof TypeChartRoute
  WeaknessesRoute: typeof WeaknessesRoute
  ApiPokemonCaptureGuideRoute: typeof ApiPokemonCaptureGuideRoute
  ApiPokemonPoolsRoute: typeof ApiPokemonPoolsRoute
  BackendProxySplatRoute: typeof BackendProxySplatRoute
  GameGenerationRoute: typeof GameGenerationRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weaknesses': {
      id: '/weaknesses'
      path: '/weaknesses'
      fullPath: '/weaknesses'
      preLoaderRoute: typeof WeaknessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type-chart': {
      id: '/type-chart'
      path: '/type-chart'
      fullPath: '/type-chart'
      preLoaderRoute: typeof TypeChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$generation': {
      id: '/game/$generation'
      path: '/game/$generation'
      fullPath: '/game/$generation'
      preLoaderRoute: typeof GameGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-proxy/$': {
      id: '/backend-proxy/$'
      path: '/backend-proxy/$'
      fullPath: '/backend-proxy/$'
      preLoaderRoute: typeof BackendProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pokemon-pools': {
      id: '/api/pokemon-pools'
      path: '/api/pokemon-pools'
      fullPath: '/api/pokemon-pools'
      preLoaderRoute: typeof ApiPokemonPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pokemon-capture-guide': {
      id: '/api/pokemon-capture-guide'
      path: '/api/pokemon-capture-guide'
      fullPath: '/api/pokemon-capture-guide'
      preLoaderRoute: typeof ApiPokemonCaptureGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/admin': {
      id: '/_authenticated/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AuthenticatedSettingsAdminRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAdminRoute: typeof AuthenticatedSettingsAdminRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAdminRoute: AuthenticatedSettingsAdminRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TypeChartRoute: TypeChartRoute,
  WeaknessesRoute: WeaknessesRoute,
  ApiPokemonCaptureGuideRoute: ApiPokemonCaptureGuideRoute,
  ApiPokemonPoolsRoute: ApiPokemonPoolsRoute,
  BackendProxySplatRoute: BackendProxySplatRoute,
  GameGenerationRoute: GameGenerationRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
